// Code generated by "stringer -type=MajorVersion"; DO NOT EDIT.

package mhdr

import "strconv"

const _MajorVersion_name = "LoRaWANR1MajorVersion"

var _MajorVersion_index = [...]uint8{0, 21}

func (i MajorVersion) String() string {
	if i >= MajorVersion(len(_MajorVersion_index)-1) {
		return "MajorVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MajorVersion_name[_MajorVersion_index[i]:_MajorVersion_index[i+1]]
}
