// Code generated by "stringer -type=MType"; DO NOT EDIT.

package mhdr

import "strconv"

const _MType_name = "JoinRequestMessageTypeJoinAcceptMessageTypeUnconfirmedDataUpMessageTypeUnconfirmedDataDownMessageTypeConfirmedDataUpMessageTypeConfirmedDataDownMessageTypeRFUMessageTypeProprietaryMessageType"

var _MType_index = [...]uint8{0, 22, 43, 71, 101, 127, 155, 169, 191}

func (i MType) String() string {
	if i >= MType(len(_MType_index)-1) {
		return "MType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MType_name[_MType_index[i]:_MType_index[i+1]]
}
